export const apiTagTypes = [
  "Parent",
  "Child",
  "Announcement",
  "Schedule",
  "Grade",
  "Attendance",
  "Notice",
  "Agenda",
  "Album",
  "Activity",
  "ExamSchedule",
  "School",
  "Parents",
  "Students",
  "Lookups",
  "Teachers",
  "Classes",
  "Courses",
  "Teaches",
  "TeacherSupervisors",
  "Sections",
  "DashboardAnnouncements",
  "DashboardNotices",
  "DashboardNoticeTypes",
  "DashboardActivities",
  "DashboardTeacherTasks",
  "DashboardAlbums",
  "DashboardWeeklySchedules",
  "DashboardExamSchedules",
  "Registrations",
  "DashboardGrades",
  "DashboardGradeForms",
  "DashboardAttendances",
  "DashboardAttendanceReasons",
  "DashboardAgendas",
  "DashboardAgendaSections",
  "DashboardSessions",
  "DashboardSettings",
  "DashboardOverview",
] as const;

export type ApiTagType = (typeof apiTagTypes)[number];
